---
###################################################################################
# GitHub workflow to automatically create a PR against all forward active branches,
# when there is a PR on 'rel-*' branch created.
#
# 1. It checks if the PR already exist and if so, does not create one.
# 2. In future we can enhance it to read the branch name from Jira label or
#    equivalent and then create PR. This way we can extend it to multiple
#    forward merges.
###################################################################################
name: Create PR for double merge
on:
  pull_request:
    types: [closed]
    branches:
      - 'rel-*'

jobs:
  create-pr-for-double-merge:
    if: github.event.pull_request.merged == true
    uses: TessellDevelopment/tessell-ci/.github/workflows/create_double_commit.yml@main
    secrets: inherit
