---
###################################################################################
# GitHub workflow to automatically create a PR against 'main' branch,
# when there is a PR on 'rel-*' branch created.
#
# 1. It checks if the PR already exist and if so, does not create one.
# 2. In future we can enhance it to read the branch name from Jira label or
#    equivalent and then create PR. This way we can extend it to multiple
#    forward merges.
###################################################################################
name: Create tag on release branch
on:
  pull_request:
    types: [closed]
    branches:
      - 'rel-*'
      - 'main'

jobs:
  create-tag-on-merge:
    uses: TessellDevelopment/tessell-ci/.github/workflows/create_tag.yml@main
    secrets: inherit
