
# This is a basic workflow to help you get started with Actions
name: Tessell Pipelines Code Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'rel-*'
      - 'TS-*' 
      - 'revert-*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    uses: TessellDevelopment/tessell-ci/.github/workflows/build_go_library.yaml@TDEVOPS-597
    secrets: inherit
    with:
      exporter_config:  '{\"linux\": \"mongodb\"}'
      exporter_name: mongodb-exporter
